#!/usr/bin/env zsh

set -euxo pipefail

# Requirements:
# 1. https://zmk.dev/docs/development/setup
# 2. checkout zmk repo to feat/pointers-move-scroll on petejohansson's repo

build_and_copy () {
    local side=$1
    west build \
        -b nice_nano_v2 -- \
        -DSHIELD=dactyl_7x7_$side \
        -DZMK_CONFIG="/home/vitstark/Repositories/zmk-config"

    cp "./build/zephyr/zmk.uf2" "$CURRENT_DIR/build/dactyl_7x7_$side.uf2"
}

CURRENT_DIR="$(pwd)"
CONFIG_DIR="$(pwd)/config"

DEFAULTZMKAPPDIR="$HOME/Repositories/zmk/app"
ZMK_APP_DIR="${1:-$DEFAULTZMKAPPDIR}"

mkdir -p $CURRENT_DIR/build

pushd $ZMK_APP_DIR

build_and_copy left
build_and_copy right

popd